# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
5*np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [6]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [15]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [18]:
np.random.rand(1)

array([0.82964499])

In [20]:
np.random.rand(25)

array([0.56848035, 0.46166905, 0.78331177, 0.01084132, 0.03855275,
       0.54703029, 0.62426826, 0.22747103, 0.73730387, 0.09006204,
       0.32940135, 0.56747487, 0.58406466, 0.42715182, 0.50686462,
       0.34211849, 0.78302488, 0.98342338, 0.6234925 , 0.60988236,
       0.16413967, 0.05140695, 0.33338235, 0.916874  , 0.14425179])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

array([ 1.32031013,  1.6798602 , -0.42985892, -1.53116655,  0.85753232,
        0.87339938,  0.35668636, -1.47491157,  0.15349697,  0.99530727,
       -0.94865451, -1.69174783,  1.57525349, -0.70615234,  0.10991879,
       -0.49478947,  1.08279872,  0.76488333, -2.3039931 ,  0.35401124,
       -0.45454399, -0.64754649, -0.29391671,  0.02339861,  0.38272124])

#### Create the following matrix:

In [24]:
np.random.random_sample((10,10))

array([[0.41556243, 0.82170835, 0.30115892, 0.96896877, 0.21378065,
        0.30989325, 0.62539276, 0.48524494, 0.90809586, 0.33150048],
       [0.66328021, 0.48876072, 0.64239155, 0.94713518, 0.13557024,
        0.27824512, 0.62681434, 0.17448272, 0.10674537, 0.10348882],
       [0.89937398, 0.41546392, 0.44361384, 0.65793669, 0.35839589,
        0.51707961, 0.49400702, 0.23641755, 0.62755934, 0.66035878],
       [0.00415749, 0.70455047, 0.47337899, 0.27711564, 0.66833942,
        0.01489494, 0.58654878, 0.4700033 , 0.94422104, 0.025592  ],
       [0.43518206, 0.35412405, 0.30433018, 0.36013787, 0.73247433,
        0.86408277, 0.25539956, 0.68848316, 0.79590822, 0.505685  ],
       [0.40993401, 0.68802627, 0.30079544, 0.33131534, 0.67186813,
        0.18513715, 0.24037277, 0.22517924, 0.26347995, 0.84942707],
       [0.00822266, 0.48539959, 0.02723643, 0.96963946, 0.29031135,
        0.01781783, 0.72871381, 0.10942277, 0.42817958, 0.54379139],
       [0.00656643, 0.59020678, 0.3810960

#### Create an array of 20 linearly spaced points between 0 and 1:

In [25]:
np.linspace(0,1.,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [26]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [36]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [39]:
mat[3,4]

20

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [43]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [44]:
mat[4]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [45]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [47]:
np.sum(mat)

325

325

#### Get the standard deviation of the values in mat

In [48]:
np.std(mat)

7.211102550927978

7.2111025509279782

#### Get the sum of all the columns in mat

In [50]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

array([55, 60, 65, 70, 75])

# Great Job!