# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [92]:
import numpy as np
from numpy.random import randint as ri

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [93]:
mat1 = ri(0,10,9).reshape(3,3)
mat2 = ri(0,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)


print("\nDivision\n------------------\n", mat1/mat2)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", 3*mat1 - 2*mat2)


print("\nAddition of a scalar (100)\n-------------------------\n", mat1+100)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",pow(mat1,1/2))


1st Matrix of random single-digit numbers
----------------------------------------
 [[8 9 5]
 [6 9 9]
 [6 1 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[6 6 4]
 [4 4 3]
 [0 2 5]]

Addition
------------------
 [[14 15  9]
 [10 13 12]
 [ 6  3 13]]

Multiplication
------------------
 [[48 54 20]
 [24 36 27]
 [ 0  2 40]]

Division
------------------
 [[1.33333333 1.5        1.25      ]
 [1.5        2.25       3.        ]
 [       inf 0.5        1.6       ]]

Linear combination: 3*A - 2*B
-----------------------------
 [[12 15  7]
 [10 19 21]
 [18 -1 14]]

Addition of a scalar (100)
-------------------------
 [[108 109 105]
 [106 109 109]
 [106 101 108]]

Exponentiation, matrix cubed here
----------------------------------------
 [[512 729 125]
 [216 729 729]
 [216   1 512]]

Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[2.82842712 3.         2.23606798]
 [2.44948974 3.         3.        ]
 [2.44

C:\Users\kaustubh\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()


Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [94]:
from numpy.random import randint as ri
mat1 = ri(0,10,9).reshape(3,3)
mat2 = ri(0,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=0))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1, axis=1))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat2,axis=0))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))


mat1 = ri(1,100,9).reshape(3,3)
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[8 6 2]
 [3 6 7]
 [3 9 5]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[4 7 1]
 [0 7 6]
 [0 2 9]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 49

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [14 21 14]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [16 16 17]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [ 96 126 135]

Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [ 0 98 54]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 5.444444444444445

Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 2.26

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [95]:
##Solution
a=ri(0,100,9).reshape(3,3)
a.reshape(9,1)

array([[62],
       [20],
       [21],
       [24],
       [52],
       [93],
       [19],
       [94],
       [12]])

### 4.Sort

In [96]:
A = ri(1,101,10) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [80 20 44 10 55  9 58 40 99 24]

Here is the sorted vector
 -------------------------------------------------- 
 [ 9 10 20 24 40 44 55 58 80 99]


In [97]:
M = ri(0,101,25).reshape(5,5) #  5*5 Matrix of random interegrs
M

array([[ 10,  77,   2,   4, 100],
       [ 99,  34,  86,  33,  90],
       [ 43,  36,   5,   5,  21],
       [ 16,  19,  19,   0,  43],
       [ 53,  96,  67,  83,  53]])

In [98]:
M = ri(0,101,25).reshape(5,5) #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M,axis=1)) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M,axis=0))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[ 80  30  26  36  34]
 [ 44  42  44  14  93]
 [ 22 100  56  51  17]
 [  2  49  14  70  20]
 [ 51  47   4  96   5]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[ 26  30  34  36  80]
 [ 14  42  44  44  93]
 [ 17  22  51  56 100]
 [  2  14  20  49  70]
 [  4   5  47  51  96]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[  2  30   4  14   5]
 [ 22  42  14  36  17]
 [ 44  47  26  51  20]
 [ 51  49  44  70  34]
 [ 80 100  56  96  93]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [99]:
# Fill the following ***** with appropriate solution.
a=ri(0,10,10)
b=ri(0,10,10)
c=ri(0,10,10)

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", np.max(a))
print("Max of b:",np.max(b))


print("Max of a location:", np.argmax(a))
print("Max of b location:", np.argmax(b))
print("Max of c location:", np.argmax(c))

print("Min of a:", np.min(a))
print("Min of b:", np.min(b))


print("Min of a location:", np.argmin(a))
print("Min of b location:", np.argmin(b))
print("Min of c location:", np.argmin(c))



a: [6 6 9 9 3 1 5 9 5 8]
b: [3 4 8 8 8 7 1 5 1 0]
c: [8 6 9 9 7 0 6 0 0 4]
Max of a: 9
Max of b: 8
Max of a location: 2
Max of b location: 2
Max of c location: 2
Min of a: 1
Min of b: 0
Min of a location: 5
Min of b location: 9
Min of c location: 5


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [100]:

mat1 = ri(0,10,9).reshape(3,3)
mat2 = ri(0,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.mod(mat1, mat2))



1st Matrix of random single-digit numbers
----------------------------------------
 [[9 3 9]
 [6 9 1]
 [8 9 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[7 2 8]
 [2 9 5]
 [0 6 8]]

Sq-root of 1st matrix using np
------------------
 [[3.         1.73205081 3.        ]
 [2.44948974 3.         1.        ]
 [2.82842712 3.         2.82842712]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[8.10308393e+03 2.00855369e+01 8.10308393e+03]
 [4.03428793e+02 8.10308393e+03 2.71828183e+00]
 [2.98095799e+03 8.10308393e+03 2.98095799e+03]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.95424251 0.47712125 0.95424251]
 [0.77815125 0.95424251 0.        ]
 [0.90308999 0.95424251 0.90308999]]

Modulo reminder using np
 -------------------------------------------------- 
 [[2 1 1]
 [0 0 1]
 [0 3 0]]


C:\Users\kaustubh\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: RuntimeWarning: divide by zero encountered in remainder


### 7.Generating matrices from distributions

In [101]:
import numpy.random as r

print("Random number generation (from Uniform distribution)")
print(r.ranf(6).reshape(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
nordis = r.randn(6).reshape(2,3)
print(nordis)

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(r.randint(1,100,10).reshape(2,5)) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",r.randint(1,7,20)) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.86329484 0.93157856 0.22831709]
 [0.11424944 0.40508416 0.9290347 ]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.26202762  0.39727365  0.18112469]
 [ 1.26801232 -0.08462431 -2.43259206]]
Random integer vector: [78 40 91  8 22 59 46  4  6 11]

Random integer matrix
[[57 43 58 40 46]
 [ 5 59 31 41 51]]

20 samples drawn from a dice throw: [6 3 1 5 6 1 3 3 1 5 5 2 1 5 5 3 5 4 4 2]


### 8.Find the nearest value from a given number in an array using NumPy.

In [102]:
#Steps
#Create an array of 5 random element from 1 to 12
#Suppose find the nearest values of 10 in an array so set value=10
#find the index where difference is minimum and get the element
ranarr = r.random(5)*12
ranarr.sort()
print(ranarr)
value=10
bLast = False
nS = np.searchsorted(ranarr,value)
if (nS == len(ranarr)):
    nS-=1
    bLast = True

if (bLast):
    print('Nearest value is: ' + str(ranarr[nS]))
else:
    if np.abs(ranarr[nS-1]-value) < np.abs(ranarr[nS]-value):
        print('Nearest value is: ' + str(ranarr[nS-1]))
    else:
        print('Nearest value is: ' + str(ranarr[nS]))


[ 3.4852466   4.62831258  7.22317494  9.42868264 11.70545338]
Nearest value is: 9.428682641140597


### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [103]:
#[i,j for i in range(0,3) for j in range(0,i)]
mat=np.array([[i*j for i in range(0,3)] for j in range(0,3)])
print(mat)

[[0 0 0]
 [0 1 2]
 [0 2 4]]
